### ISSUE TITLE
Challenge submission stuck at Submitted

### ISSUE THREAD

**Issue by agupt013** [epic-kitchens/C3-Action-Anticipation#1]
Hi,
I submitted my files to the test server on the following link. However, my submission is stuck in the "Submitted" state. Can you please take a look?

Link: https://competitions.codalab.org/competitions/20071#learn_the_details
Error log: Standard error for submission #4 by agupt013.

![image](https://user-images.githubusercontent.com/36806314/98929309-cc36d180-248f-11eb-96a4-5c7f23d09b72.png)

**Comment by antoninofurnari** [comment]
Hi, 
Aparently your submission has been correctly evaluated (see below). Can you try now? Maybe it was a temporary problem with codalab servers.

![image](https://user-images.githubusercontent.com/20006211/98961477-e3180b00-2505-11eb-80e6-e9a94a45fcc5.png)

For reference, "Finished" means that the submission has been evaluated and "False" means that it has not been sent to the leaderboard.

**Comment by agupt013** [comment]
Hi,
How much time should it take for the submission to process? My new submission is again stuck in Submitted state.
My earlier submission returned results quickly but last two submissions are taking longer.

**Comment by antoninofurnari** [comment]
I see your most recent submittion (Nov. 13, 2020, 8:20 p.m.) is "finished". The time required by codalab to process the submission should not be that long, but unfortunately this is out of our control. 

Maybe the longer times are due to the servers being under stress because of the CVPR 21 deadline?

**Comment by dimadamen** [comment]
That is right... there's a queuing system in Codalab, your job will be processed when resources are available and this is a busy time of year,
